// ============================================================================
// js/levels.js
// All 9 alignment level definitions. Data only — no game logic.
// ============================================================================

import { M2 } from './math-engine.js';

export function buildLevels() {
  return [
    {
      title: 'Level 1: Uniform Scaling',
      desc: 'Your monster needs to match the target shape. The target is twice as big in every direction.',
      obj: 'Find the 2×2 matrix that scales the monster uniformly by a factor of 2.',
      target: new M2(2, 0, 0, 2),
      validate: 'exact',
      concept: 'matrix_uniform_scaling',
      teach: `A 2×2 matrix transforms every point (x, y) in a shape using this rule:\n\n  new_x = a·x + b·y\n  new_y = c·x + d·y\n\nA "scaling" matrix only uses the diagonal — b and c stay 0. This means x and y transform independently: new_x = a·x and new_y = d·y.\n\nFor uniform scaling (same in all directions), think: what single number, when you multiply any coordinate by it, doubles the distance from the center?\n\nTry experimenting: click Preview to see what your current matrix does to the monster before committing.`,
      formulaRef: `Uniform scale: [s  0]\n               [0  s]\n(x,y) → (sx, sy)\ndet = s²  (area scales by s²)`,
      tutorQ: 'In your own words, what does the diagonal of a scaling matrix control? What would happen to the monster if the scale factor were 0.5 instead of 2?',
    },
    {
      title: 'Level 2: Non-Uniform Scaling',
      desc: 'This time the target has been stretched differently on each axis. Look closely at the shape.',
      obj: 'Find the matrix that scales x by 3 and y by 0.5.',
      target: new M2(3, 0, 0, 0.5),
      validate: 'exact',
      concept: 'matrix_nonuniform_scaling',
      teach: `When the two diagonal entries are different, each axis stretches independently:\n\n  new_x = a·x   (a controls horizontal stretch)\n  new_y = d·y   (d controls vertical stretch)\n\nThe off-diagonal entries b and c remain 0 for a pure scaling.\n\nLook at the target shape on the canvas — how does it compare to the starting monster? Is it wider or narrower? Taller or shorter? Those observations tell you whether a > 1 or a < 1, and whether d > 1 or d < 1.\n\nThe determinant (a × d) tells you the total area change.`,
      formulaRef: `Non-uniform scale: [a  0]\n                       [0  d]\n(x,y) → (ax, dy)\ndet = a·d`,
      tutorQ: 'How does stretching by different factors on each axis differ geometrically from uniform scaling? If a circle were transformed this way, what shape would it become?',
    },
    {
      title: 'Level 3: The Identity Matrix',
      desc: 'The monster and the target are identical. No transformation needed — but you still have to write a matrix.',
      obj: 'Enter the matrix that leaves every point exactly where it is.',
      target: new M2(1, 0, 0, 1),
      validate: 'exact',
      concept: 'identity_matrix',
      teach: `In regular arithmetic, multiplying by 1 changes nothing: 5 × 1 = 5. Matrix algebra has the exact same concept — a matrix that, when applied, leaves every point untouched.\n\nThis matrix has a specific name and a specific structure. Think about what values would make:\n\n  new_x = ?·x + ?·y = x    (x unchanged)\n  new_y = ?·x + ?·y = y    (y unchanged)\n\nWhat does each entry need to be for these equations to work out?`,
      formulaRef: `Identity: [1  0]\n             [0  1]\nM·I = I·M = M  for any M\ndet(I) = 1`,
      tutorQ: 'Why is this called the "identity" matrix? How does it relate to the number 1 in ordinary multiplication? Can you think of a situation where knowing this matrix is useful?',
    },
    {
      title: 'Level 4: Shear Transformation',
      desc: 'The target has been slanted sideways. This is called a shear — and it uses the off-diagonal entries.',
      obj: 'Apply a horizontal shear: the top-right entry should be 1.5, diagonal entries stay 1.',
      target: new M2(1, 1.5, 0, 1),
      validate: 'exact',
      concept: 'shear_transformation',
      teach: `So far we've only used the diagonal. Now meet the off-diagonal entries.\n\nA horizontal shear uses the top-right entry (b):\n  new_x = x + b·y\n  new_y = y\n\nNotice: the y-coordinate never changes. Only x shifts, and by an amount that depends on how far up (y) the point is. Imagine pushing the top of a stack of cards sideways — the bottom stays still, the top moves most.\n\nThe diagonal entries stay at 1 for a pure shear. And here's a surprising fact: calculate the determinant of a shear matrix. What do you notice?`,
      formulaRef: `Horizontal shear: [1  k]\n                     [0  1]\n(x,y) → (x+ky, y)\ndet = 1  (area preserved!)`,
      tutorQ: 'A shear does not change the area of a shape, even though it distorts it. Why is that? Can you explain geometrically why the area stays the same?',
    },
    {
      title: 'Level 5: Rotation 90°',
      desc: 'The target monster has been rotated. Rotation matrices use cosine and sine of the angle.',
      obj: 'Rotate the monster exactly 90° counter-clockwise.',
      target: new M2(0, -1, 1, 0),
      validate: 'exact',
      concept: 'rotation_matrix',
      teach: `A rotation matrix for angle θ (counter-clockwise) looks like this:\n\n  [cos θ   −sin θ]\n  [sin θ    cos θ]\n\nFor this level, you need θ = 90°.\n\nHere's a useful thinking strategy: instead of memorizing, reason from first principles. Ask yourself:\n  • Where does the point (1, 0) go after rotating 90° CCW?\n  • Where does the point (0, 1) go after rotating 90° CCW?\n\nThe COLUMNS of your rotation matrix are those destination points. This works for any rotation — and it's how mathematicians think about all matrix transformations.`,
      formulaRef: `Rotation by θ: [cos θ  −sin θ]\n               [sin θ   cos θ]\ncos 90° = 0,  sin 90° = 1\ndet = cos²θ + sin²θ = 1`,
      tutorQ: 'Why does a rotation matrix always have a determinant of 1? What does that tell you about how rotation affects the size and shape of the monster?',
    },
    {
      title: 'Level 6: Matrix Composition',
      desc: 'Two transformations applied in sequence become one combined matrix — their product.',
      obj: 'Compose: scale x by 2 first, then apply a horizontal shear of k=1. What is the result?',
      target: (new M2(1, 1, 0, 1)).mm(new M2(2, 0, 0, 1)),
      validate: 'exact',
      concept: 'matrix_composition',
      teach: `When you apply transformation A followed by transformation B, the combined effect is the matrix product B·A (note the order: B comes first in the product even though A is applied first).\n\nFor this level:\n  A = scale x by 2:   [2  0]\n                       [0  1]\n  B = horizontal shear k=1:  [1  1]\n                              [0  1]\n\nTo find the composition, multiply B·A by hand. Take each entry of the result:\n  result[row][col] = (row of B) · (col of A)\n\nTry working through one entry at a time. The matrix you enter should be the combined single matrix, not A or B separately.`,
      formulaRef: `Composition: B·A  (A applied first)\n[1 1]·[2 0] = ?\n[0 1] [0 1]\nOrder matters: AB ≠ BA in general`,
      tutorQ: 'Why does the ORDER of matrix multiplication matter? Give a real-world example where doing two operations in different orders gives a different result.',
    },
    {
      title: 'Level 7: Inverse — Undo!',
      desc: 'The monster was stretched by a known matrix. The inverse matrix undoes that transformation.',
      obj: 'The monster was transformed by [4, 0 / 0, 2]. Enter its inverse matrix.',
      target: (new M2(4, 0, 0, 2)).inv(),
      validate: 'exact',
      concept: 'inverse_matrix',
      teach: `Every invertible transformation has an "undo" button — the inverse matrix M⁻¹.\n\nThe key property: M · M⁻¹ = I (the identity).\n\nFor a diagonal matrix [a, 0 / 0, b], think about it entry by entry:\n  • The top-left entry of M is a. After applying M, the x-coordinate was multiplied by a.\n  • To undo that multiplication, what do you multiply by?\n  • Same logic for the bottom-right entry d.\n\nWhat are 1/4 and 1/2 as decimals? Try entering those. You can verify your answer mentally: if you apply M then M⁻¹, do you get back to the identity?`,
      formulaRef: `Diagonal inverse: [a  0]⁻¹ = [1/a   0 ]\n               [0  b]       [ 0   1/b]\nCheck: M·M⁻¹ = I\ndet(M⁻¹) = 1/det(M)`,
      tutorQ: 'If a matrix has a determinant of 0, it has no inverse. Why does that make sense geometrically? What does det=0 mean about what the transformation does to space?',
    },
    {
      title: 'Level 8: Determinant Challenge',
      desc: 'The determinant measures how much a matrix scales area. There are many valid answers here.',
      obj: 'Enter any diagonal matrix whose determinant equals exactly 6.',
      target: new M2(3, 0, 0, 2),
      validate: 'det6',
      concept: 'determinant_area',
      teach: `The determinant of a matrix tells you the area scaling factor. If you apply a matrix to a 1×1 square, the resulting parallelogram has area equal to |det|.\n\nFor a diagonal matrix [a, 0 / 0, b]:\n  det = a × b\n\nThere is no single correct answer here — any pair of numbers that multiply to 6 will work. Think of it like: 6 = 1×6 = 2×3 = 6×1 = (−2)×(−3)...\n\nA few things to consider:\n  • What does a negative determinant mean? (Hint: look at the monster orientation)\n  • What does det > 1 vs det < 1 mean for the monster's size?\n\nTry a few different pairs and use Preview to see what each one does.`,
      formulaRef: `Diagonal det: [a  0] → det = a·b\n               [0  b]\ndet > 0: orientation preserved\ndet < 0: orientation flipped\n|det| = area scale factor`,
      tutorQ: 'You found one matrix with det=6. Could you find another one that is NOT diagonal but still has det=6? How would you construct it? What does the determinant tell us beyond just scaling?',
    },
    {
      title: 'Level 9: Reflection',
      desc: 'A reflection flips the monster across an axis. Unlike rotation, it reverses orientation.',
      obj: 'Reflect the monster across the x-axis (y coordinate negates, x stays).',
      target: new M2(1, 0, 0, -1),
      validate: 'exact',
      concept: 'reflection_matrix',
      teach: `A reflection flips a shape across a line. For the x-axis, think about what happens to each point:\n  • A point above the axis moves to the same distance below.\n  • A point below the axis moves to the same distance above.\n  • x is completely unchanged.\n\nSo the transformation sends (x, y) to (x, −y). Write out what that means for each entry of the 2×2 matrix:\n  new_x = ?·x + ?·y = x\n  new_y = ?·x + ?·y = −y\n\nAfter you find the matrix, calculate its determinant. Is it positive or negative? Think about why reflection and rotation give different signs for the determinant.`,
      formulaRef: `x-axis reflection: [1   0]\n                     [0  −1]\n(x,y) → (x, −y)\ndet = −1  (orientation flips!)`,
      tutorQ: 'Reflections and rotations both preserve the size and shape of a figure, but their determinants are different (+1 vs −1). What does this difference in sign tell us about orientation? Can you think of a physical analogy?',
    },
  ];
}